// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED HOOKS FOR INVOICEFLOW
// Generated by Auto-SaaS God Mode
// ═══════════════════════════════════════════════════════════════

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { orpcClient } from "@shared/lib/orpc-client";
import type { Invoices } from "@/types/invoiceflow";
import type { InvoiceItems } from "@/types/invoiceflow";
import type { InvoiceClients } from "@/types/invoiceflow";

// ═══════════════════════════════════════════════════════════════
// Invoices Hooks
// ═══════════════════════════════════════════════════════════════

export function useInvoices() {
  return useQuery({
    queryKey: ["invoiceflow", "invoices"],
    queryFn: async () => {
      try {
        const result = await orpcClient.invoiceflow.invoices.list();
        return result.data || [];
      } catch (error) {
        console.error("Error fetching invoices:", error);
        return [];
      }
    },
  });
}

export function useInvoice(id: string | null) {
  const { data, ...rest } = useInvoices();
  const invoice = id ? data?.find((item: any) => item.id === id) : null;
  return { data: invoice, ...rest };
}

export function useCreateInvoice() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Invoices, 'id' | 'created_at' | 'updated_at'>) => {
      return await orpcClient.invoiceflow.invoices.create(data as any);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoices"] });
    },
  });
}

export function useUpdateInvoice() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: {
      id: string;
      client_name?: string;
      client_email?: string | null;
      invoice_number?: string;
      issue_date?: string;
      due_date?: string | null;
      status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
      subtotal?: number;
      tax_rate?: number;
      tax_amount?: number;
      total?: number;
      notes?: string | null;
    }) => {
      return await orpcClient.invoiceflow.invoices.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoices"] });
    },
  });
}

export function useDeleteInvoice() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.invoiceflow.invoices.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoices"] });
    },
  });
}

// ═══════════════════════════════════════════════════════════════
// InvoiceItems Hooks
// ═══════════════════════════════════════════════════════════════

export function useInvoiceItems() {
  return useQuery({
    queryKey: ["invoiceflow", "invoice_items"],
    queryFn: async () => {
      try {
        const result = await orpcClient.invoiceflow.invoice_items.list();
        return result.data || [];
      } catch (error) {
        console.error("Error fetching invoice_items:", error);
        return [];
      }
    },
  });
}

export function useInvoice_item(id: string | null) {
  const { data, ...rest } = useInvoiceItems();
  const invoice_item = id ? data?.find((item: any) => item.id === id) : null;
  return { data: invoice_item, ...rest };
}

export function useCreateInvoice_item() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<InvoiceItems, 'id' | 'created_at' | 'updated_at'>) => {
      return await orpcClient.invoiceflow.invoice_items.create(data as any);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_items"] });
    },
  });
}

// export function useUpdateInvoice_item() {
//   const queryClient = useQueryClient();
//   return useMutation({
//     mutationFn: async (data: { id: string } & Partial<InvoiceItems>) => {
//       return await orpcClient.invoiceflow.invoice_items.update(data);
//     },
//     onSuccess: () => {
//       queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_items"] });
//     },
//   });
// }

// export function useDeleteInvoice_item() {
//   const queryClient = useQueryClient();
//   return useMutation({
//     mutationFn: async (id: string) => {
//       return await orpcClient.invoiceflow.invoice_items.delete({ id });
//     },
//     onSuccess: () => {
//       queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_items"] });
//     },
//   });
// }

// ═══════════════════════════════════════════════════════════════
// InvoiceClients Hooks
// ═══════════════════════════════════════════════════════════════

export function useInvoiceClients() {
  return useQuery({
    queryKey: ["invoiceflow", "invoice_clients"],
    queryFn: async () => {
      try {
        const result = await orpcClient.invoiceflow.invoice_clients.list();
        return result.data || [];
      } catch (error) {
        console.error("Error fetching invoice_clients:", error);
        return [];
      }
    },
  });
}

export function useInvoice_client(id: string | null) {
  const { data, ...rest } = useInvoiceClients();
  const invoice_client = id ? data?.find((item: any) => item.id === id) : null;
  return { data: invoice_client, ...rest };
}

export function useCreateInvoice_client() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<InvoiceClients, 'id' | 'created_at' | 'updated_at'>) => {
      return await orpcClient.invoiceflow.invoice_clients.create(data as any);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_clients"] });
    },
  });
}

// export function useUpdateInvoice_client() {
//   const queryClient = useQueryClient();
//   return useMutation({
//     mutationFn: async (data: { id: string } & Partial<InvoiceClients>) => {
//       return await orpcClient.invoiceflow.invoice_clients.update(data);
//     },
//     onSuccess: () => {
//       queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_clients"] });
//     },
//   });
// }

// export function useDeleteInvoice_client() {
//   const queryClient = useQueryClient();
//   return useMutation({
//     mutationFn: async (id: string) => {
//       return await orpcClient.invoiceflow.invoice_clients.delete({ id });
//     },
//     onSuccess: () => {
//       queryClient.invalidateQueries({ queryKey: ["invoiceflow", "invoice_clients"] });
//     },
//   });
// }

