// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED HOOKS FOR TASKFLOW
// Generated by Auto-SaaS God Mode
// ═══════════════════════════════════════════════════════════════

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { orpcClient } from "@shared/lib/orpc-client";
import type { Tasks } from "@/types/taskflow";

// ═══════════════════════════════════════════════════════════════
// Tasks Hooks
// ═══════════════════════════════════════════════════════════════

export function useTasks(options?: {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
  status?: string;
}) {
  return useQuery({
    queryKey: ["taskflow", "tasks", options],
    queryFn: async () => {
      const result = await orpcClient.taskflow.tasks.list(options);
      return result;
    },
  });
}

export function useTask(id: string | null) {
  return useQuery({
    queryKey: ["taskflow", "tasks", id],
    queryFn: async () => {
      if (!id) return null;
      const result = await orpcClient.taskflow.tasks.get({ id });
      return result.data || null;
    },
    enabled: !!id,
  });
}

export function useCreateTask() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: Omit<Tasks, 'id' | 'created_at' | 'updated_at' | 'organization_id'>) => {
      return await orpcClient.taskflow.tasks.create(data as unknown as Parameters<typeof orpcClient.taskflow.tasks.create>[0]);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["taskflow", "tasks"] });
    },
  });
}

export function useUpdateTask() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (data: { id: string; [key: string]: any }) => {
      return await orpcClient.taskflow.tasks.update(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["taskflow", "tasks"] });
    },
  });
}

export function useDeleteTask() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      return await orpcClient.taskflow.tasks.delete({ id });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["taskflow", "tasks"] });
    },
  });
}

