// ============================================================================
// CONTENTFLOW AI - TypeScript Types
// Generated by Auto-SaaS Builder - Layer 8
// Blueprint: contentflow-ai
// ============================================================================

import { z } from 'zod';

// ============================================================================
// DATABASE TYPES (matching SQL schema)
// ============================================================================

/** Agencia de marketing que usa ContentFlow */
export interface Agency {
  id: string;
  user_id: string;
  name: string;
  brand_voice: BrandVoice | null;
  created_at: Date;
}

/** Configuración de voz de marca (JSONB) */
export interface BrandVoice {
  tone: 'professional' | 'casual' | 'friendly' | 'formal' | 'playful';
  keywords: string[];
  avoid_words: string[];
  language: string;
}

/** Cliente de una agencia */
export interface AgencyClient {
  id: string;
  agency_id: string;
  name: string;
  industry: string | null;
  approval_token: string | null;
  created_at: Date;
}

/** Entrada del calendario de contenido */
export interface ContentCalendar {
  id: string;
  client_id: string;
  scheduled_date: Date;
  platform: ContentPlatform;
  content_text: string;
  status: ContentStatus;
  created_at: Date;
}

/** Plataformas soportadas */
export type ContentPlatform = 
  | 'instagram' 
  | 'facebook' 
  | 'twitter' 
  | 'linkedin' 
  | 'tiktok' 
  | 'blog';

/** Estados del contenido */
export type ContentStatus = 
  | 'draft' 
  | 'pending_approval' 
  | 'approved' 
  | 'scheduled' 
  | 'published' 
  | 'rejected';

// ============================================================================
// INSERT/UPDATE TYPES
// ============================================================================

/** Para crear nueva agencia */
export type NewAgency = Omit<Agency, 'id' | 'created_at'>;

/** Para actualizar agencia */
export type UpdateAgency = Partial<Omit<Agency, 'id' | 'user_id' | 'created_at'>>;

/** Para crear nuevo cliente */
export type NewAgencyClient = Omit<AgencyClient, 'id' | 'created_at' | 'approval_token'>;

/** Para actualizar cliente */
export type UpdateAgencyClient = Partial<Omit<AgencyClient, 'id' | 'agency_id' | 'created_at'>>;

/** Para crear nueva entrada de calendario */
export type NewContentCalendar = Omit<ContentCalendar, 'id' | 'created_at'>;

/** Para actualizar entrada de calendario */
export type UpdateContentCalendar = Partial<Omit<ContentCalendar, 'id' | 'client_id' | 'created_at'>>;

// ============================================================================
// ZOD SCHEMAS (runtime validation)
// ============================================================================

export const BrandVoiceSchema = z.object({
  tone: z.enum(['professional', 'casual', 'friendly', 'formal', 'playful']),
  keywords: z.array(z.string()),
  avoid_words: z.array(z.string()),
  language: z.string().default('es')
});

export const AgencySchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  brand_voice: BrandVoiceSchema.nullable(),
  created_at: z.coerce.date()
});

export const NewAgencySchema = z.object({
  user_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  brand_voice: BrandVoiceSchema.nullable().optional()
});

export const UpdateAgencySchema = z.object({
  name: z.string().min(1).max(255).optional(),
  brand_voice: BrandVoiceSchema.nullable().optional()
});

export const AgencyClientSchema = z.object({
  id: z.string().uuid(),
  agency_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  industry: z.string().max(100).nullable(),
  approval_token: z.string().nullable(),
  created_at: z.coerce.date()
});

export const NewAgencyClientSchema = z.object({
  agency_id: z.string().uuid(),
  name: z.string().min(1).max(255),
  industry: z.string().max(100).nullable().optional()
});

export const UpdateAgencyClientSchema = z.object({
  name: z.string().min(1).max(255).optional(),
  industry: z.string().max(100).nullable().optional()
});

export const ContentPlatformSchema = z.enum([
  'instagram', 'facebook', 'twitter', 'linkedin', 'tiktok', 'blog'
]);

export const ContentStatusSchema = z.enum([
  'draft', 'pending_approval', 'approved', 'scheduled', 'published', 'rejected'
]);

export const ContentCalendarSchema = z.object({
  id: z.string().uuid(),
  client_id: z.string().uuid(),
  scheduled_date: z.coerce.date(),
  platform: ContentPlatformSchema,
  content_text: z.string().min(1).max(5000),
  status: ContentStatusSchema,
  created_at: z.coerce.date()
});

export const NewContentCalendarSchema = z.object({
  client_id: z.string().uuid(),
  scheduled_date: z.coerce.date(),
  platform: ContentPlatformSchema,
  content_text: z.string().min(1).max(5000),
  status: ContentStatusSchema.default('draft')
});

export const UpdateContentCalendarSchema = z.object({
  scheduled_date: z.coerce.date().optional(),
  platform: ContentPlatformSchema.optional(),
  content_text: z.string().min(1).max(5000).optional(),
  status: ContentStatusSchema.optional()
});

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
  };
}

// ============================================================================
// CONTENTFLOW-SPECIFIC TYPES
// ============================================================================

/** Contenido con relaciones expandidas */
export interface ContentCalendarWithClient extends ContentCalendar {
  client: AgencyClient;
}

/** Cliente con su agencia */
export interface AgencyClientWithAgency extends AgencyClient {
  agency: Agency;
}

/** Agencia con todos sus clientes */
export interface AgencyWithClients extends Agency {
  clients: AgencyClient[];
}

/** Request para generar contenido con IA */
export interface GenerateContentRequest {
  client_id: string;
  platforms: ContentPlatform[];
  start_date: Date;
  days: number;
  topics?: string[];
  custom_instructions?: string;
}

/** Response de generación de contenido */
export interface GenerateContentResponse {
  success: boolean;
  generated: ContentCalendar[];
  tokens_used?: number;
}

// ============================================================================
// MARKETINGOS INTEGRATION TYPES
// ============================================================================

/** Metadata para webhook a MarketingOS */
export interface ContentFlowWebhookPayload {
  blueprint_id: 'contentflow-ai';
  event: 'content_generated' | 'content_approved' | 'content_published';
  agency_id: string;
  client_id?: string;
  content_ids?: string[];
  timestamp: string;
  metadata?: Record<string, unknown>;
}

